package main

import (
	"database/sql"
	"fmt"
	"reflect"
	"strings"

	"github.com/99designs/gqlgen/graphql"
	validator "github.com/syssam/go-validator"
)

// --- Struct definitions ---

// UpdateUserInput uses gqlgen's graphql.Omittable for GraphQL mutation inputs.
// Generated by gqlgen with nullable_input_omittable: true in gqlgen.yml.
//
// RegisterAutoUnwrap matches ALL Omittable[T] variants with a single registration.
// The validator auto-builds optimized unwrappers using cached method indices.
type UpdateUserInput struct {
	Name  graphql.Omittable[*string] `json:"name" valid:"required"`
	Email graphql.Omittable[*string] `json:"email" valid:"required,email"`
	Age   graphql.Omittable[int]     `json:"age" valid:"min=0"`
}

// User uses database/sql nullable types for database models.
// sql.Null* types don't have IsSet()/Value() methods, so we register them
// explicitly with RegisterCustomTypeFunc for best performance.
type User struct {
	Name  sql.NullString  `json:"name" valid:"required"`
	Email sql.NullString  `json:"email" valid:"required,email"`
	Age   sql.NullInt64   `json:"age" valid:"min=18"`
	Score sql.NullFloat64 `json:"score" valid:"between=0|100"`
}

func init() {
	// --- graphql.Omittable: use RegisterAutoUnwrap ---
	// One registration handles ALL Omittable[T] variants (300+ types).
	// Specify the method names — the validator builds optimized unwrappers
	// with cached method indices automatically.
	validator.RegisterAutoUnwrap(
		func(t reflect.Type) bool {
			return strings.HasPrefix(t.Name(), "Omittable[") &&
				strings.Contains(t.PkgPath(), "gqlgen")
		},
		"IsSet", // Omittable.IsSet() bool — returns whether the value is set
		"Value", // Omittable.Value() T   — returns the inner value
	)

	// --- sql.Null*: use RegisterCustomTypeFunc ---
	// sql.Null* types use a .Valid field instead of IsSet()/Value() methods,
	// so register each type explicitly for best performance.
	validator.RegisterCustomTypeFunc(func(n sql.NullString) (any, bool) {
		if !n.Valid {
			return nil, false
		}
		return n.String, true
	})
	validator.RegisterCustomTypeFunc(func(n sql.NullInt64) (any, bool) {
		if !n.Valid {
			return nil, false
		}
		return n.Int64, true
	})
	validator.RegisterCustomTypeFunc(func(n sql.NullFloat64) (any, bool) {
		if !n.Valid {
			return nil, false
		}
		return n.Float64, true
	})
}

func main() {
	fmt.Println("===== graphql.Omittable examples (RegisterAutoUnwrap) =====")
	omittableExamples()

	fmt.Println("\n===== sql.Null examples (RegisterCustomTypeFunc) =====")
	sqlNullExamples()
}

func omittableExamples() {
	name := "Alice"
	email := "alice@example.com"

	// All fields set — valid
	fmt.Println("\n--- All fields set (valid) ---")
	input := &UpdateUserInput{
		Name:  graphql.OmittableOf(&name),
		Email: graphql.OmittableOf(&email),
		Age:   graphql.OmittableOf(25),
	}
	printResult(validator.ValidateStruct(input))

	// Name omitted — required fails
	fmt.Println("\n--- Name omitted (required) ---")
	input2 := &UpdateUserInput{
		Email: graphql.OmittableOf(&email),
		Age:   graphql.OmittableOf(25),
	}
	printResult(validator.ValidateStruct(input2))

	// Age omitted — no required, skipped
	fmt.Println("\n--- Age omitted (optional) ---")
	input3 := &UpdateUserInput{
		Name:  graphql.OmittableOf(&name),
		Email: graphql.OmittableOf(&email),
	}
	printResult(validator.ValidateStruct(input3))

	// Name set to null
	fmt.Println("\n--- Name set to null ---")
	input4 := &UpdateUserInput{
		Name:  graphql.OmittableOf[*string](nil),
		Email: graphql.OmittableOf(&email),
	}
	printResult(validator.ValidateStruct(input4))
}

func sqlNullExamples() {
	// All fields valid
	fmt.Println("\n--- All fields valid ---")
	user := &User{
		Name:  sql.NullString{String: "Alice", Valid: true},
		Email: sql.NullString{String: "alice@example.com", Valid: true},
		Age:   sql.NullInt64{Int64: 25, Valid: true},
		Score: sql.NullFloat64{Float64: 95.5, Valid: true},
	}
	printResult(validator.ValidateStruct(user))

	// Name is NULL — required fails
	fmt.Println("\n--- Name is NULL (required) ---")
	user2 := &User{
		Name:  sql.NullString{Valid: false},
		Email: sql.NullString{String: "alice@example.com", Valid: true},
		Age:   sql.NullInt64{Int64: 25, Valid: true},
		Score: sql.NullFloat64{Float64: 95.5, Valid: true},
	}
	printResult(validator.ValidateStruct(user2))

	// Age is NULL — no required, skipped
	fmt.Println("\n--- Age is NULL (optional) ---")
	user3 := &User{
		Name:  sql.NullString{String: "Alice", Valid: true},
		Email: sql.NullString{String: "alice@example.com", Valid: true},
		Age:   sql.NullInt64{Valid: false},
		Score: sql.NullFloat64{Float64: 95.5, Valid: true},
	}
	printResult(validator.ValidateStruct(user3))
}

func printResult(err error) {
	if err == nil {
		fmt.Println("Valid!")
		return
	}
	for _, e := range err.(validator.Errors) {
		fmt.Println("Error:", e)
	}
}
