comment: off
coverage:
  status:
    project:
      default:
        target: 75%
        threshold: 2%
        base: auto
    patch:
      default:
        target: 70%
        threshold: 5%
        base: auto