package validator

// MessageMap is a map of string, that can be used as error message for ValidateStruct function.
var MessageMap = map[string]string{
	"accepted":             "The {{.Attribute}} must be accepted.",
	"acceptedIf":           "The {{.Attribute}} must be accepted when {{.Other}} is {{.Value}}.",
	"activeUrl":            "The {{.Attribute}} is not a valid URL.",
	"after":                "The {{.Attribute}} must be a date after {{.Date}}.",
	"afterOrEqual":         "The {{.Attribute}} must be a date after or equal to {{.Date}}.",
	"alpha":                "The {{.Attribute}} may only contain letters.",
	"alphaDash":            "The {{.Attribute}} may only contain letters, numbers, dashes and underscores.",
	"alphaNum":             "The {{.Attribute}} may only contain letters and numbers.",
	"array":                "The {{.Attribute}} must be an array.",
	"ascii":                "The {{.Attribute}} must only contain ASCII characters.",
	"before":               "The {{.Attribute}} must be a date before {{.Date}}.",
	"beforeOrEqual":        "The {{.Attribute}} must be a date before or equal to {{.Date}}.",
	"between.numeric":      "The {{.Attribute}} must be between {{.Min}} and {{.Max}}.",
	"between.file":         "The {{.Attribute}} must be between {{.Min}} and {{.Max}} kilobytes.",
	"between.string":       "The {{.Attribute}} must be between {{.Min}} and {{.Max}} characters.",
	"between.array":        "The {{.Attribute}} must have between {{.Min}} and {{.Max}} items.",
	"boolean":              "The {{.Attribute}} field must be true or false.",
	"confirmed":            "The {{.Attribute}} confirmation does not match.",
	"contains":             "The {{.Attribute}} must contain {{.Values}}.",
	"date":                 "The {{.Attribute}} is not a valid date.",
	"dateFormat":           "The {{.Attribute}} does not match the format {{.Format}}.",
	"decimal":              "The {{.Attribute}} must have {{.Decimal}} decimal places.",
	"declined":             "The {{.Attribute}} must be declined.",
	"declinedIf":           "The {{.Attribute}} must be declined when {{.Other}} is {{.Value}}.",
	"different":            "The {{.Attribute}} and {{.Other}} must be different.",
	"digits":               "The {{.Attribute}} must be {{.Digits}} digits.",
	"digitsBetween":        "The {{.Attribute}} must be between {{.Min}} and {{.Max}} digits.",
	"dimensions":           "The {{.Attribute}} has invalid image dimensions.",
	"distinct":             "The {{.Attribute}} field has a duplicate value.",
	"doesntContain":        "The {{.Attribute}} must not contain {{.Values}}.",
	"doesntEndWith":        "The {{.Attribute}} must not end with {{.Values}}.",
	"doesntStartWith":      "The {{.Attribute}} must not start with {{.Values}}.",
	"email":                "The {{.Attribute}} must be a valid email address.",
	"endsWith":             "The {{.Attribute}} must end with {{.Values}}.",
	"exists":               "The selected {{.Attribute}} is invalid.",
	"file":                 "The {{.Attribute}} must be a file.",
	"filled":               "The {{.Attribute}} field must have a value.",
	"hexColor":             "The {{.Attribute}} must be a valid hexadecimal color code.",
	"gt.numeric":           "The {{.Attribute}} must be greater than {{.Value}}.",
	"gt.file":              "The {{.Attribute}} must be greater than {{.Value}} kilobytes.",
	"gt.string":            "The {{.Attribute}} must be greater than {{.Value}} characters.",
	"gt.array":             "The {{.Attribute}} must have greater than {{.Value}} items.",
	"gte.numeric":          "The {{.Attribute}} must be greater than or equal {{.Value}}.",
	"gte.file":             "The {{.Attribute}} must be greater than or equal {{.Value}} kilobytes.",
	"gte.string":           "The {{.Attribute}} must be greater than or equal {{.Value}} characters.",
	"gte.array":            "The {{.Attribute}} must have {{.Value}} items or more.",
	"image":                "The {{.Attribute}} must be an image.",
	"in":                   "The selected {{.Attribute}} is invalid.",
	"inArray":              "The {{.Attribute}} field does not exist in {{.Other}}.",
	"integer":              "The {{.Attribute}} must be an integer.",
	"ip":                   "The {{.Attribute}} must be a valid IP address.",
	"ipv4":                 "The {{.Attribute}} must be a valid IPv4 address.",
	"ipv6":                 "The {{.Attribute}} must be a valid IPv6 address.",
	"json":                 "The {{.Attribute}} must be a valid JSON string.",
	"list":                 "The {{.Attribute}} field must be a list.",
	"lowercase":            "The {{.Attribute}} must be lowercase.",
	"lt.numeric":           "The {{.Attribute}} must be less than {{.Value}}.",
	"lt.file":              "The {{.Attribute}} must be less than {{.Value}} kilobytes.",
	"lt.string":            "The {{.Attribute}} must be less than {{.Value}} characters.",
	"lt.array":             "The {{.Attribute}} must have less than {{.Value}} items.",
	"lte.numeric":          "The {{.Attribute}} must be less than or equal {{.Value}}.",
	"lte.file":             "The {{.Attribute}} must be less than or equal {{.Value}} kilobytes.",
	"lte.string":           "The {{.Attribute}} must be less than or equal {{.Value}} characters.",
	"lte.array":            "The {{.Attribute}} must not have more than {{.Value}} items.",
	"max.numeric":          "The {{.Attribute}} may not be greater than {{.Max}}.",
	"max.file":             "The {{.Attribute}} may not be greater than {{.Max}} kilobytes.",
	"max.string":           "The {{.Attribute}} may not be greater than {{.Max}} characters.",
	"max.array":            "The {{.Attribute}} may not have more than {{.Max}} items.",
	"macAddress":           "The {{.Attribute}} must be a valid MAC address.",
	"maxDigits":            "The {{.Attribute}} must not have more than {{.Max}} digits.",
	"mimes":                "The {{.Attribute}} must be a file of type: {{.Values}}.",
	"mimetypes":            "The {{.Attribute}} must be a file of type: {{.Values}}.",
	"min.numeric":          "The {{.Attribute}} must be at least {{.Min}}.",
	"min.file":             "The {{.Attribute}} must be at least {{.Min}} kilobytes.",
	"min.string":           "The {{.Attribute}} must be at least {{.Min}} characters.",
	"min.array":            "The {{.Attribute}} must have at least {{.Min}} items.",
	"minDigits":            "The {{.Attribute}} must have at least {{.Min}} digits.",
	"missing":              "The {{.Attribute}} field must be missing.",
	"missingIf":            "The {{.Attribute}} field must be missing when {{.Other}} is {{.Value}}.",
	"missingUnless":        "The {{.Attribute}} field must be missing unless {{.Other}} is {{.Value}}.",
	"missingWith":          "The {{.Attribute}} field must be missing when {{.Values}} is present.",
	"missingWithAll":       "The {{.Attribute}} field must be missing when {{.Values}} are present.",
	"multipleOf":           "The {{.Attribute}} must be a multiple of {{.Value}}.",
	"notIn":                "The selected {{.Attribute}} is invalid.",
	"notRegex":             "The {{.Attribute}} format is invalid.",
	"numeric":              "The {{.Attribute}} must be a number.",
	"present":              "The {{.Attribute}} field must be present.",
	"presentIf":            "The {{.Attribute}} field must be present when {{.Other}} is {{.Value}}.",
	"presentUnless":        "The {{.Attribute}} field must be present unless {{.Other}} is {{.Value}}.",
	"presentWith":          "The {{.Attribute}} field must be present when {{.Values}} is present.",
	"presentWithAll":       "The {{.Attribute}} field must be present when {{.Values}} are present.",
	"prohibited":           "The {{.Attribute}} field is prohibited.",
	"prohibitedIf":         "The {{.Attribute}} field is prohibited when {{.Other}} is {{.Value}}.",
	"prohibitedIfAccepted": "The {{.Attribute}} field is prohibited when {{.Other}} is accepted.",
	"prohibitedIfDeclined": "The {{.Attribute}} field is prohibited when {{.Other}} is declined.",
	"prohibitedUnless":     "The {{.Attribute}} field is prohibited unless {{.Other}} is {{.Value}}.",
	"prohibits":            "The {{.Attribute}} field prohibits {{.Values}} from being present.",
	"regex":                "The {{.Attribute}} format is invalid.",
	"required":             "The {{.Attribute}} field is required.",
	"requiredIf":           "The {{.Attribute}} field is required when {{.Other}} is {{.Value}}.",
	"requiredArrayKeys":    "The {{.Attribute}} field must contain entries for: {{.Values}}.",
	"requiredIfAccepted":   "The {{.Attribute}} field is required when {{.Other}} is accepted.",
	"requiredIfDeclined":   "The {{.Attribute}} field is required when {{.Other}} is declined.",
	"requiredUnless":       "The {{.Attribute}} field is required unless {{.Other}} is in {{.Values}}.",
	"requiredWith":         "The {{.Attribute}} field is required when {{.Values}} is present.",
	"requiredWithAll":      "The {{.Attribute}} field is required when {{.Values}} is present.",
	"requiredWithout":      "The {{.Attribute}} field is required when {{.Values}} is not present.",
	"requiredWithoutAll":   "The {{.Attribute}} field is required when none of {{.Values}} are present.",
	"same":                 "The {{.Attribute}} and {{.Other}} must match.",
	"size.numeric":         "The {{.Attribute}} must be {{.Size}}.",
	"size.file":            "The {{.Attribute}} must be {{.Size}} kilobytes.",
	"size.string":          "The {{.Attribute}} must be {{.Size}} characters.",
	"size.array":           "The {{.Attribute}} must contain {{.Size}} items.",
	"startsWith":           "The {{.Attribute}} must start with {{.Values}}.",
	"string":               "The {{.Attribute}} must be a string.",
	"timezone":             "The {{.Attribute}} must be a valid zone.",
	"ulid":                 "The {{.Attribute}} must be a valid ULID.",
	"unique":               "The {{.Attribute}} has already been taken.",
	"uploaded":             "The {{.Attribute}} failed to upload.",
	"uppercase":            "The {{.Attribute}} must be uppercase.",
	"uuid3":                "The {{.Attribute}} format is invalid.",
	"uuid4":                "The {{.Attribute}} format is invalid.",
	"uuid5":                "The {{.Attribute}} format is invalid.",
	"uuid":                 "The {{.Attribute}} format is invalid.",
}
